package:
  name: am_tdm
  version: 0.1

source:
  path: .

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python=3.10
    - pandas=1.5.3
    - scipy=1.10.1
    - numpy=1.24.3
    - matplotlib=3.7.1

test:
  imports:
    - am_tdm

about:
  home: 'https://github.com/radumust18/python-animal-td-model'
  license: 'MIT License'
  summary: 'Copyright (c) 2022 Radu-Ioan Mustatea'